blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('', home, name='home'),
    path('post/', post, name='post'),
    path('login/', login_page, name ='login'),
    path('search/', search, name ='search'),
    path('custom-admin/', custom_admin, name ='custom_admin'),
    path('categories/', all_category, name ='categories'),
    path('categories/<str:category_name>/', postfilter, name ='categories'),
    path('custom-admin-category/', custom_admin_category, name ='custom_admin_category'),
    path('users-info/', user_info, name ='user_info'),
    # path('login/', auth_views.LoginView.as_view(template_name= 'blog/login.html'), name ='login'),
    path('logout/', log_out, name ='logout'),
    path('edit-profile/', editprofile, name ='editprofile'),
    path('userprofile/', userprofile, name ='userprofile'),
    path('register/', register, name ='register'),
    path('contact/', contact, name ='contact'),
    path('my-posts/', my_post, name ='my-post'),
    path('likes', like_mypost, name ='likes'),
    path('create-post/', userpost, name ='userpost'),
    path('like', like_home, name ='likess'),
    path('users-info/<int:p_id>/', user_details, name ='user_details'),
    path('custom-admin/add-post', admin_add_post, name ='admin_add_post'),
    path('custom-admin/register', admin_registration, name ='admin_registration'),
    path('custom-admin/<slug>/update', custom_admin_update, name ='custom_admin_update'),
    path('custom-admin/<slug>/delete', custom_admin_delete, name ='custom_admin_delete'),
    path('post/<slug>/user-info/', userdetails, name ='userdetails'),
    path('post/<slug>/update-post/', update_post, name ='update_post'),
    path('post/<slug>/delete/', delete_post, name ='delete'),
    path('post/like', like_post, name ='like'),
    # path('edit-profile/', edit_profile, name ='edit_profile'),
    path('change-password/', change_password, name ='change_password'),
    path('my-posts/<slug>/', mypost_details, name ='my-postDetails'),
    path('post/<slug>/', Details, name='details'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from blog import urls
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls)),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from PIL import Image
# Create your models here.
import random
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from myblog.utils import unique_slug_generator
from ckeditor.fields import RichTextField

class Video(models.Model):
	video = models.FileField()
	title = models.CharField(max_length=3242)

	def videoURL(self):
		try:
			url = self.video.url
		except:
			url = ''
		return url

class Category(models.Model):
	category_name = models.CharField(max_length=93)
	image = models.ImageField()
	date  = models.DateTimeField(auto_now_add=True)
	approve = models.BooleanField(default=False)

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url
	def __str__(self):
		return self.category_name
# choices = Category.objects.all().values_list('category_name', 'category_name')
# choice_list = []

# for item in choices:
# 	choice_list.append(item)
class Post(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	title = models.CharField(max_length=10000)
	date = models.DateTimeField(auto_now_add=True)
	image = models.ImageField()
	text = RichTextField()
	publish = models.BooleanField(default= False)
	slug = models.SlugField(max_length=2500, null=False, blank=True)
	likes = models.ManyToManyField(User, related_name='likes', blank=True)
	view_count = models.IntegerField(default=0)



	class Meta:
		db_table = "post"

	@property
	def num_likes(self):
		return self.likes.all().count()
	def __str__(self):
		return f'{self.title} || Post'
	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url
	def save(self, *args, **kwargs):
		super(Post,self).save(*args, **kwargs)
		img = Image.open(self.image.path)
		if img.height < 1000 or img.width < 800:
			output_size = (1000, 800)
			img.thumbnail(output_size)
			img.save(self.image.path)

def slug_generator(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender= Post)

LIKE_CHOICES = [
	('Like', 'Like'),
	('Unlike', 'Unlike'),
]

class Like(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	value = models.CharField(choices=LIKE_CHOICES, default='Like', max_length=30)

	class Meta:
		db_table = "like"

	def __str__(self):
		return self.user.username

class Newsletter(models.Model):
	email = models.EmailField()

	def __str__(self):
		return self.email


class PostDetail(models.Model):
	post = models.OneToOneField(Post, on_delete=models.CASCADE)

	def __str__(self):
		return f"{self.post.title} || Post Details"




class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	gender = models.CharField(max_length=6, default = 'null', choices=(('Male', 'Male'), ('Female', 'Female')), blank=True)
	image = models.ImageField(default='avatar.png', max_length= 100)
	facebook = models.CharField(default='facebook', max_length= 100)
	twitter = models.CharField(default='twitter', max_length= 100)
	linkedin = models.CharField(default='linkedin', max_length= 100)
	website_link = models.URLField(default='https://www.abc.com')
	about_you = models.TextField()

	class Meta:
		db_table = "userprofile"

	def __str__(self):
		return f"{self.user.username} || Profile"
	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url

	def save(self, *args, **kwargs):
		super(UserProfile,self).save(*args, **kwargs)
		img = Image.open(self.image.path)
		if img.height > 301 or img.width > 326:
			output_size = (301, 326)
			img.thumbnail(output_size)
			img.save(self.image.path)

class UserInfo(models.Model):
	username = models.CharField(max_length=40)
	password = models.CharField(max_length=40)
	agree = models.BooleanField(default=False)

	class Meta:
		db_table = "userinfo"

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	# reply = models.ForeignKey('self', null=True,on_delete=models.CASCADE)
	userprofile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = "comment"
	def __str__(self):
		return f'{self.post.title} || Comment'


class Contact(models.Model):
	name = models.CharField(max_length=50)
	email = models.EmailField(max_length=50)
	body = models.TextField()

	class Meta:
		db_table = "contact"

blog/views.py
from django.shortcuts import render, get_object_or_404,HttpResponse
from .models import *
from .forms import *
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.contrib import messages
from .filters import *
from django.contrib.auth.forms import UsernameField
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.views.generic import ListView, CreateView
from .models import *
import time
from django.http import JsonResponse
from django.db.models import Q
import time
from datetime import datetime
from django.db.models import Count
import sys
from bs4 import BeautifulSoup as bs
import time
import requests
import pandas as pd
import random

now = datetime.now()
def home(request):
    if request.method == 'POST':
        forms = NewsletterForm(request.POST)
        if forms.is_valid():
            forms.save()
            messages.success(request,'Email Submitted')
            return redirect('/')
    else:
        forms = NewsletterForm()
    post1= Post.objects.filter(publish=True).order_by('-date')
    post2= Post.objects.filter(publish=True).order_by('date')
    post3= Post.objects.filter(publish=True).order_by('-view_count')
    category = Category.objects.filter(approve=True)
    catego = Category.objects.filter(approve=True).annotate(posts_count = Count('post'))
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        name = request.POST['name']
        if Category.objects.filter(name=name).exists():
            messages.error(request,  'Category name already exists')
        else:
            form.save()
            return redirect('/')
    else:
        form = CategoryForm()
    context = {'forms': forms,
              'post1':post1,
              'form': form,
              'category': category,
              'post2':post2,
              'post3':post3,
              'catego': catego
               }
    template_name = 'blog/home.html'
    return render(request, template_name, context)

# @login_required
def all_category(request):
    context = {}
    category= Category.objects.filter(approve=True)
    filters = CategoryFilter(request.GET, queryset= category)
    filtered_post = filters.qs
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES)
        category_name = request.POST['category_name']
        if Category.objects.filter(category_name=category_name).exists():
            messages.success(request, 'Category name already exists')
            return redirect('/categories')
        else:
            form.save()
            messages.success(request, 'Category Created, waiting for approval')
            return redirect('/categories')
    else:
        form = CategoryForm()
        context['form'] = form
    context = {
        'filters': filters,
        'category': filtered_post,
        'form': form,
    }
    return render(request, 'blog/category.html', context)

def postfilter(request, category_name):
	category= Category.objects.get(category_name=category_name)
	post = Post.objects.filter(category=category)
	post_length = len(post)
	context = {
	'category':category,
	'title': "All Category",
	'post': post,
	'post_length': post_length,
	}
	return render(request, 'blog/postfilters.html', context)



def post(request):
    post = Post.objects.filter(publish= True).order_by('-id')
    filters = PostFilter(request.GET, queryset=post)
    filtered_post = filters.qs
    paginator = Paginator(filtered_post, 9)
    page = request.GET.get('page')
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        # category = request.POST['category']
        # title = request.POST['title']
        # image = request.FILES['image']
        # text = request.POST['text']
        # post = Post.objects.create(user=request.user,category=category,title=title,image=image,text=text)
        post = form.save(commit=False)
        post.user = request.user
        post.publish = True
        post.save()
        messages.success(request, 'Post Created, waiting for approval')
        return redirect('/post')
    else:
        form = PostForm()
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)
    context = {
        'paginate': post_list,
        'page': page,
        'forms': forms,
        'post':  filtered_post,
        'filter': filters,
        'form': form,
        'forms': forms,
    }
    return render(request, 'blog/post.html', context)
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'



def Details(request, slug):
    posts = Post.objects.filter(publish=True).order_by('-id')
    post = get_object_or_404(Post, slug = slug)
    post.view_count += 1
    post.save()
    postdetails = PostDetail.objects.filter(post=post)
    filters = DetailsFilter(request.GET, queryset=postdetails)
    postdetails = filters.qs
    if request.method == 'POST':
        forms = NewsletterForm(request.POST)
        if forms.is_valid():
            forms.save()
            messages.success(request,'Email Submitted')
            return HttpResponseRedirect(reverse('details', args=(slug,)))
    else:
        forms = NewsletterForm()
    comment = Comment.objects.filter(post=post)
    print(time.timezone)

    dt = now.strftime('%d/%m/%Y %H:%M:%S')
    print(dt)
    if request.method == "POST":
        form = CommentForm(request.POST , None)
        body = request.POST['body']
        if is_ajax(request=request):
            if form.is_valid():
                Comment.objects.get_or_create(post=post, userprofile= request.user.userprofile,user=request.user,body=body)
                instance = form.save(commit=False)
                instance.user = request.user
                return JsonResponse({
                    'body': instance.body,
                    'created': dt,
                    'user': instance.user.username,
                    # 'image': request.user.userprofile.image.url,
                })
            # return HttpResponseRedirect(reverse('details', args=(slug,)))
    else:
        form = CommentForm()
    context = {
        'posts': posts,
        'post': post,
        'postdetails': postdetails,
        'comment': comment,
        'form': form,
        'forms': forms,
        'filters': filters,
    }

    return render(request, 'blog/post_details.html', context)

@login_required
def userdetails(request, slug):
    post = get_object_or_404(Post, slug = slug)
    postdetails = PostDetail.objects.filter(post=post)
    context = {
        'post': post,
        'postdetails': postdetails
    }
    return render(request, 'blog/userdetails.html', context)

def register(request):
    if request.user.is_authenticated:
        return redirect('/')
        messages.success(request, 'You Are Alredy Logged In')
    else:
        context = {}
        if request.method == "POST":
            users = request.POST.get('username')
            email = request.POST.get('email')
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            password3 = request.POST['password1']
            checkbox = request.POST.get('checkbox')
            username = users.lower()
            print(checkbox)
            if User.objects.filter(email=email).exists():
                messages.error(request, 'Email Already Exist')
                return redirect('/register')
            elif User.objects.filter(username=username).exists():
                messages.error(request, 'Username Has Been Taken')
                return redirect('/register')
            elif password1 != password2:
                messages.error(request, 'Password does not match')
                return redirect('/register')
            # elif checkbox
            else:
                user_info = UserInfo.objects.create(username=username, password=password3, agree= True)
                user = User.objects.create_user(email=email,password=password1, username=username)
                user.save()
                messages.success(request,'Registration successfully')
                UserProfile.objects.get_or_create(user=user)
                print(checkbox)
                return redirect('/login')

        return render(request,'blog/registration.html', context)

def login_page(request):
    context = {}
    if request.method == "POST":
        form = LoginForm(request.POST)
        context['form'] = form
        next = request.GET.get('next')
        username = request.POST.get('username')
        password = request.POST.get('password')
        use = username.lower()
        user = authenticate(username=use, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.success(request, f'Login Successful')
                if next:
                    return redirect(next)
                return HttpResponseRedirect('/')
            else:
                return HttpResponse('Acdd')
        else:
            invalid = 'Invalid Credentials'
            context['invalid'] = invalid
    else:
        form = LoginForm()
        context['form'] = form
    return render(request,'blog/login.html', context)

def log_out(request):
    logout(request)
    return redirect('/')

@login_required
def userpost(request):
    if request.method == 'POST':
        category = request.POST['category']
        title = request.POST['title']
        image = request.FILES['image']
        text = request.POST['text']

blog/templates/blog/admin.html
{% extends 'blog/adminbase.html' %}
{% block content %}
{% load static %}
<script src="{% static 'js/jquery.js' %}"></script>
		<div class="main-content">
				{% if messages %}
				{% for message in messages %}
			<div class="success">
            	<p>{{message}}</p>
            </div>
            	{% endfor %}
				{% endif %}
                <table>
                    <tr>
                        <th>ID</th>
                        <th>Users</th>
                        <th>Category</th>
                        <th>Title</th>
                        <th>Publish</th>
                        <th>Likes</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    {% for posts in post %}
                    <tr>
                        <td>{{posts.id}}</td>
                        <td>{{posts.user.username.capitalize}}</td>
                        <td>{{posts.category.capitalize}}</td>
                        <td>{{posts.title.capitalize}}</td>
                        <td>{{posts.publish}}</td>
                        <td>{{posts.likes.count}}</td>
                        <td><a href="/custom-admin/{{posts.slug}}/update"><button class="edit">Edit</button></a></td>
                        <td><a href="/custom-admin/{{posts.slug}}/delete"><button class="delete">Delete</button></a></td>
                    </tr>
                    {% endfor %}        
                </table>
                <h5>{{post.count}} Post{{post|pluralize}}</h5>
                
		</div>
	</div>
	{% endblock %}
</body>
</html>
<script>
    function closeDiv(){
        $('.success').fadeOut(500)
    }
    setTimeout('closeDiv()', 3000)
</script>

blog/templates/blog/dashboard.html
<html>
<head>
	{% load static %}
	<script src="{% static 'js/jquery.js' %}"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<style type="text/css">
			*{
			padding: 0px;
      margin: 0px;
      font-size: 14px;;
      
			font-family: sans-serif;
			overflow-x: hidden;
		}
		#main {
			display: grid;
			grid-template-columns: 20% 80%;
		}
		.nav-links {
			background-color: rgba(0,0,0,0.5);
			position: absolute;
			top: 23%;
			left: -30%; 
			width: 30%;
			display: block;
			transition: .5s;
		}
		.sidebar {
			background-color: rgba(0,0,0,0.5);
			height: 110vh;
			color: white;
		}
		.sidebar .img {
			text-align: center;
			margin-top: 20px;
		}
		.sidebar img {
			border-radius: 40%;
			width: 60%;
		}
		.sidebar ul {
			margin-top: 0px;

		}
		.sidebar ul li {
			list-style: none;
		}
		.sidebar ul li a {
			color: white;
      display: block;
      font-size: 14px;;
			text-decoration: none;
			padding: 20px 20px 20px 20px;
		}
		.sidebar ul li a:hover {
			background-color: rgba(0,0,0,0.4);
		}
		.details {
			width: 600px;
			border: 1px solid #ccc;
			border-radius: 6px;
			margin: 45px auto;
		}
		.burger {
			float: right;
			margin-top: 9px;
			display: none;
		}
		.burg1,.burg2,.burg3 {
			width: 20px;
			height: 3px;
			background-color: white;
			margin-top: 4px;
			transition: .7s;
		}
		.details .head {
			background-color: rgba(0,0,0,0.1);
			padding: 15px;
			text-align: center;
		}
		@media only screen and (max-width: 700px) {
			#main {
				display: block;
			}	
			.sidebar {
				height: 23vh;
			}
			.content {
				display: flex;
				justify-content: space-around;
				align-items: center;
			}
			.sidebar .img {
				margin-top: 20px;
				text-align: initial;
			}
			.content ul {
				display: none;
			}
			.content .img img {
				width: 20%;
				padding-left: 0px;
			}
			.burger {
				display: block;
			}
			.burg1.burg {
				transform: rotate(-45deg) translate(-5px, 6px);
				transition: .7s;
			}
			.burg2.burg {
				opacity: 0;
				transition: .7s;
			}
			.burg3.burg {
				transform: rotate(45deg) translate(-5px, -6px);
				transition: .7s;
			}
			.nav-links.burg {
				display: block;
				left: 10%;
				transition: .5s;
			}
		}
	</style>
</head>
<body>
	<div id="main">
		<div class="sidebar">
			<div class="content">
				<div class="img">
					<img src="{{user.userprofile.imageURL}}">
					<h2 style="margin-top: 10px; ">{{user.username.capitalize}}</h2>
				</div>
				<ul>
					<li><a href="{% url 'userprofile' %}">View Profile</a></li>
					<li><a href="{% url 'edit_profile' %}">Edit Profile</a></li>
					<li><a href="{% url 'my-post' %}">My Posts</a></li>
					<li><a href="{% url 'change_password' %}">Change Password</a></li>
					<li><a href="{% url 'logout' %}">Logout</a></li>
					<li><a href="{% url 'home' %}">Go to Home</a></li>
				</ul>
				<div class="burger" onclick="tog()">
					<div class="burg1"></div>
					<div class="burg2"></div>
					<div class="burg3"></div>
				</div>
			</div>
			<div class="nav-links">
				<ul>
					<li><a href="{% url 'userprofile' %}">View Profile</a></li>
					<li><a href="{% url 'edit_profile' %}">Edit Profile</a></li>
					<li><a href="{% url 'my-post' %}">My Posts</a></li>
					<li><a href="{% url 'change_password' %}">Change Password</a></li>
					<li><a href="{% url 'logout' %}">Logout</a></li>
					<li><a href="{% url 'home' %}">Go to Home</a></li>
				</ul>
			</div>
		</div>
		{% block content %}
		{% endblock %}
</div>
</body>
<script type="text/javascript">
		function tog() {
			var y = document.querySelector('.burg1')
			var z = document.querySelector('.burg3')
			var a = document.querySelector('.burg2')
			var b = document.querySelector('.nav-links')
			y.classList.toggle('burg')
			a.classList.toggle('burg')
			b.classList.toggle('burg')
			z.classList.toggle('burg')
		}
	</script>
<script>

	// $(document).on('submit', '#form', function(e){
	// 	e.preventDefault();
		
	// 	$.ajax({
	// 		type: 'POST',
	// 		url: '/edit-profile/',
	// 		data: {
	// 			name: $('#id_name').val(),
	// 			email: $('#id_email').val(),
	// 			username: $('#id_username').val(),
	// 			first_name: $('#id_first_name').val(),
	// 			last_name: $('#id_last_name').val(),
	// 			gender: $('#id_gender').val(),
	// 			facebook: $('#id_facebook').val(),
	// 			website_link: $('#id_website_link').val(),
	// 			twitter: $('#id_twitter').val(),
	// 			linkedin: $('#id_linkedin').val(),
	// 			csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
	// 		},
	// 		success:function(){
	// 			alert('Update Successfully')
				

	// 			}

	// 	});
	

</script>
</html>

blog/templates/blog/profile.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<script src="{% static 'js/jquery.js' %}"></script>
	<title>Sam Profile</title>
	<style type="text/css">
		* {
			padding: 0px;
			margin: 0px;
			font-family: sans-serif;
		}
		.form {
			width: 650px;
			border-radius: 0px 0px 8px 8px;
			border: 1px solid #ccc;
			padding: 20px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.1), 0 6px 20px 0 rgba(0, 0, 0, 0.1);
		}
		h2 {
			background-color: rgba(0,0,0,0.4);
			border-radius: 8px 8px 0px 0px;
			padding: 10px;
			text-align: center;
			width: 672px;
				
		}
		#name {
			display: inline-grid;
			grid-template-columns: 1fr 1fr;
			grid-gap: 30px;

		}

		#id_username,#id_first_name, #id_last_name, #id_email, #id_image, #id_facebook, #id_twitter, #id_linkedin, #id_youtube {
			width: 290px;
			border: 1px solid #ccc;
			border-radius: 2px;
			padding: 8px 5px;
			margin-top: 4px;
		}
		select {
			width: 303px;
			border: 1px solid #ccc;
			border-radius: 2px;
			padding: 0px 5px;
		}
		button {
			width: 100px;
			padding: 8px 13px;
		}
		.gride {
			display: inline-grid;
			}
		#name a {
			display: none;
		}
	</style>
</head>
<body>
	<form method="POST" id="form" enctype="multipart/form-data">
		<h2>Users Profile Form</h2>
		<div class="form">
			{% csrf_token %}
			<div id='name'>
				<div class="gride">
					{{u_form.username.label}}:
					{{u_form.username}}
				</div>
				<div class="gride"> 
					{{u_form.first_name.label}}:
					{{u_form.first_name}}			
				</div>	
				<div class="gride">
					{{u_form.last_name.label}}:
					{{u_form.last_name}}
				</div>
				<div class="gride">
					{{u_form.email.label}}:
					{{u_form.email}}
				</div>
				<div class="gride">
					{{p_form.image.label}}:
					{{p_form.image}}
				</div>
				<div class="gride">
					{{p_form.gender.label}}:
					{{p_form.gender}}
				</div>
				<div class="gride">				
					{{p_form.facebook.label}}:
					{{p_form.facebook}}
				</div>
				<div class="gride">	
					{{p_form.twitter.label}}:
					{{p_form.twitter}}
				</div>
				<div class="gride">	
					{{p_form.linkedin.label}}:
					{{p_form.linkedin}}
				</div>
				<div class="gride">
					{{p_form.youtube.label}}:
					{{p_form.youtube}}
				</div>
			<button type="submit">Update</button>
			</div>
		</div> 	
	</form>
</body>
<script type="text/javascript">
	// document.getElementById('#form').addEventListener('change', save_data())

	// 	function save_data(){
	// 			var name =  $('#id_name').val();
	// 			var email = $('#id_email').val();
	// 			var username = $('#id_username').val();
	// 			var first_name = $('#id_first_name').val();
	// 			var last_name = $('#id_last_name').val();
	// 			var image = $('#id_image').val();
	// 			var gender = $('#id_gender').val();
	// 			var facebook = $('#id_facebook').val();
	// 			var youtube = $('#id_youtube').val();
	// 			var twitter = $('#id_twitter').val();
	// 			var linkedin = $('#id_linkedin').val();
	// 			var token = '{{csrf_token}}';
	// 	}
		
	// 	$.ajax({
	// 		type: 'POST',
	// 		headers: {'X-CSRFToken': token},
	// 		data: {
				
	// 		},
	// 		success:function(){

	// 		}


	$(document).on('submit', '#form', function(e){
		e.preventDefault();
		
		$.ajax({
			type: 'POST',
			url: '/userprofile/',
			data: {
				name: $('#id_name').val(),
				email: $('#id_email').val(),
				username: $('#id_username').val(),
				first_name: $('#id_first_name').val(),
				last_name: $('#id_last_name').val(),
				image: $('#id_image').val(),
				gender: $('#id_gender').val(),
				facebook: $('#id_facebook').val(),
				youtube: $('#id_youtube').val(),
				twitter: $('#id_twitter').val(),
				linkedin: $('#id_linkedin').val(),
				csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
			},
			success:function(){
				alert('Update Successfully')
				location.reload()
			}

		});
	})
</script>
</html>
{% endblock %}